name: 'Install Dependencies'
description: 'Set up Python and install dependencies'
inputs:
  python-version:
    description: 'Python version'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ inputs.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt