ame: Conditional Steps Example

on: [push]

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run tests
        if: github.event_name == 'push'
        run: npm test