name: Re-Usable Steps

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/actions/setup-python/install-dependencies
        with:
          python-version: '3.9'

      - name: Run tests
        run: pytest
        env:
          PYTHONPATH: ${{ github.workspace }}

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/actions/setup-python/install-dependencies
        with:
          python-version: '3.9'

      - name: Lint code
        run: pylint calculator.py
        env:
          PYTHONPATH: ${{ github.workspace }}