name: Reusable Workflow

on:
  workflow_call:
    inputs:
      username:
        required: true
        type: string

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello, ${{ inputs.username }}!"