name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/actions/setup-node/install-dependencies
        with:
          node-version: '14'

      - name: Run tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Dependencies
        uses: ./.github/actions/setup-node/install-dependencies
        with:
          node-version: '14'

      - name: Build project
        run: npm run build